// src/lib/mentors.ts
export const mentors = [
  {
    id: 1,
    slug: 'grace-mukamana',
    name: 'Dr. Grace Mukamana',
    title: 'CEO & Founder',
    company: 'Kigali Tech Hub',
    bio: 'Leading Rwanda’s tech revolution since 2015. Helped 47+ startups raise over $2.3M in funding. Former Google Africa fellow.',
    expertise: ['Tech & Software', 'Fundraising', 'Startup Scaling', 'Product Strategy'],
    rating: 5.0,
    sessions_completed: 47,
    hourly_rate: 5000,
    available: true,
    image: '/mentors/grace.png',
    email: 'francisschooten@gmail.com',
    years_experience: 15,
    startups_mentored: 47,
    countries: 12,
    hours_mentored: 1200,
    quote: 'I’ve helped 47 startups raise $2.3M. Let’s make yours #48.',
  },
  {
    id: 2,
    slug: 'jean-paul-niyibizi',
    name: 'Jean Paul Niyibizi',
    title: 'Founder & CEO',
    company: 'Ampersand Rwanda',
    bio: 'Pioneer of electric mobility in Africa. Raised $20M+ for clean energy transport.',
    expertise: ['Green Energy', 'Manufacturing', 'Hardware', 'Climate Tech'],
    rating: 4.9,
    sessions_completed: 38,
    hourly_rate: 8000,
    available: true,
    image: '/mentors/jean-paul.png',
    email: 'francisschooten@gmail.com',
  },
  {
    id: 3,
    slug: 'aime-mugisha',
    name: 'Aimé Mugisha',
    title: 'Co-Founder & CTO',
    company: 'Irembo',
    bio: 'Built Rwanda’s digital government platform used by millions.',
    expertise: ['GovTech', 'FinTech', 'System Architecture', 'E-Government'],
    rating: 5.0,
    sessions_completed: 42,
    hourly_rate: 10000,
    available: true,
    image: '/mentors/aime.png',
    email: 'francisschooten@gmail.com',
  },
  {
    id: 4,
    slug: 'claire-uwineza',
    name: 'Claire Uwineza',
    title: 'Founder & CEO',
    company: 'VubaVuba Coffee',
    bio: 'Transformed coffee farming with direct-to-consumer model. Raised $1.8M.',
    expertise: ['Agribusiness', 'E-commerce', 'Supply Chain', 'Export Strategy'],
    rating: 4.9,
    sessions_completed: 35,
    hourly_rate: 6000,
    available: true,
    image: '/mentors/claire.png',
    email: 'francisschooten@gmail.com',
  },
  {
    id: 5,
    slug: 'emmanuel-kayitare',
    name: 'Emmanuel Kayitare',
    title: 'Former Managing Director',
    company: 'Rwanda Development Board',
    bio: 'Helped attract $2B+ FDI into Rwanda. Knows every investor in East Africa.',
    expertise: ['Investment Attraction', 'Policy', 'Public-Private Partnerships'],
    rating: 5.0,
    sessions_completed: 51,
    hourly_rate: 15000,
    available: false,
    image: '/mentors/emmanuel.png',
    email: 'francisschooten@gmail.com',
  },
  {
    id: 6,
    slug: 'hope-mutesi',
    name: 'Hope Mutesi',
    title: 'Country Director',
    company: 'Girl Effect Rwanda',
    bio: 'Built digital platforms reaching 2M+ young women.',
    expertise: ['Social Impact', 'Digital Media', 'Youth Empowerment'],
    rating: 4.8,
    sessions_completed: 29,
    hourly_rate: 7000,
    available: true,
    image: '/mentors/hope.png',
    email: 'francisschooten@gmail.com',
  },
  {
    id: 7,
    slug: 'patrick-bizimana',
    name: 'Patrick Bizimana',
    title: 'Country Manager',
    company: 'Zipline Rwanda',
    bio: 'Scaled drone delivery network across Rwanda.',
    expertise: ['Logistics', 'Drones', 'Operations', 'Healthcare Tech'],
    rating: 5.0,
    sessions_completed: 44,
    hourly_rate: 12000,
    available: true,
    image: '/mentors/patrick.png',
    email: 'francisschooten@gmail.com',
  },
  {
    id: 8,
    slug: 'diane-sayinzoga',
    name: 'Diane Sayinzoga',
    title: 'CEO',
    company: 'Rwanda Finance Limited',
    bio: 'Building Kigali International Financial Centre.',
    expertise: ['Finance', 'Capital Markets', 'Financial Inclusion'],
    rating: 4.9,
    sessions_completed: 39,
    hourly_rate: 18000,
    available: true,
    image: '/mentors/diane.png',
    email: 'francisschooten@gmail.com',
  },
  {
    id: 9,
    slug: 'yvette-ishimwe',
    name: 'Yvette Ishimwe',
    title: 'Founder & CEO',
    company: 'Irere Foods',
    bio: 'Exports premium Rwandan honey and superfoods globally.',
    expertise: ['Agribusiness', 'Export', 'Branding', 'Food Processing'],
    rating: 4.9,
    sessions_completed: 33,
    hourly_rate: 6500,
    available: true,
    image: '/mentors/yvette.png',
    email: 'francisschooten@gmail.com',
  },
  {
    id: 10,
    slug: 'olivier-murenzi',
    name: 'Olivier Murenzi',
    title: 'Co-Founder',
    company: 'Amini AI',
    bio: 'AI startup backed by Google & Microsoft. Climate intelligence for Africa.',
    expertise: ['Artificial Intelligence', 'Climate Tech', 'Data Science'],
    rating: 5.0,
    sessions_completed: 31,
    hourly_rate: 9000,
    available: true,
    image: '/mentors/olivier.png',
    email: 'francisschooten@gmail.com',
  },
] as const;

export type Mentor = typeof mentors[number];